In [3]:
import numpy as np

In [4]:
# Обычный массив
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
# Используем функции `zeros`, `ones`, `arange` 
zeros = np.zeros(7)
ones = np.ones((6,9))
ara = np.arange(0, 9, 3)

zeros, ones, ara

(array([0., 0., 0., 0., 0., 0., 0.]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 array([0, 3, 6]))

In [8]:
# Демонстрация атрибутов
print("a:", a)
print("Shape:", a.shape)
print("ndim:", a.ndim)
print("dtype:", a.dtype)

a: [1 2 3]
Shape: (3,)
ndim: 1
dtype: int64


In [27]:
# Примеры индексирования и срезов
new_a = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Первый элемент: {new_a[0]}")
print(f"Шестой элемент: {new_a[5]}")
print(f"Девятый элемент (предпоследний): {new_a[-2]}")

print(f"Два элемента с конца: {new_a[-2:]}")
print(f"Всё, кроме двух последних: {new_a[:-2]}")
print(f"с 6 по 9 элемент: {new_a[5:9]}") # Элемент по 5 индексу не берётся :D
print(f"Каждый 3 элемент: {new_a[::3]}")

Первый элемент: 1
Шестой элемент: 6
Девятый элемент (предпоследний): 9
Два элемента с конца: [ 9 10]
Всё, кроме двух последних: [1 2 3 4 5 6 7 8]
с 6 по 9 элемент: [6 7 8 9]
Каждый 3 элемент: [ 1  4  7 10]


In [32]:
# Примеры векторных операций и базовых статистик
new1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new2 = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Сложим и умножим

print(f"Сложим new1 + new2 = {new1 + new2}")
print(f"Умножим new1 + new2 = {new1 * new2}")

print(f"Средняя величина new1 через mean: {np.mean(new1)}")

Сложим new1 + new2 = [12 14 16 18 20 22 24 26 28 30]
Умножим new1 + new2 = [ 11  24  39  56  75  96 119 144 171 200]
Средняя величина new1 через mean: 5.5
